# Generated by Django 3.0.3 on 2020-02-18 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('cover_photo', models.FileField(blank=True, upload_to='static/uploads/')),
                ('thumbnail', models.FileField(blank=True, upload_to='static/uploads/')),
                ('github_repo_link', models.CharField(blank=True, max_length=200)),
                ('deployment_link', models.CharField(blank=True, max_length=200)),
                ('further_reading', models.CharField(blank=True, max_length=200)),
                ('tutorial_reading', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Category')),
                ('tags', models.ManyToManyField(to='projects.Tag')),
            ],
        ),
    ]
